### ISSUE TITLE
Interpolate Creatinine

### ISSUE THREAD

**Issue by aegis301** [AI2MS/pyAKI#11]
Build an interpolation method for creatinine. Right now we are just using the sum, which is not ideal since there might be edge cases where reatinine was measured multiple times within an hour. Mean would be better. Also, we can forward fille the upsampled time series with the old creatinine value until we get a new one. We should also define a threshold for amount of missing data when we want to fill nan-values (e.g. if we don't have any creatinine value for 72h, we want to fill nan instead). The user should be able to apply different thresholds as needed.

**Comment by Paul-B98** [comment]
should be done with #8. I just need to do some docs
