### ISSUE TITLE
implement kdigo_uo_criterion function

### ISSUE THREAD

**Issue by aegis301** [AI2MS/pyAKI#2]
This function should for now take to numpy vectors as input: one vector containing the urine output values, one vector containing the respective timestamps. 

It should output two vectors:

1. The first vector should contain the hourly timestamps
2. The second vector should contain the kdigo stages at each hour according to the kdigo urine output criteria

**Comment by jernsting** [comment]
I have built this using pd.DataFrame instead of vectors. Seems to be more flexible. But we could of course just reimplement it.
