### ISSUE TITLE
Handle Missing Data

### ISSUE THREAD

**Issue by aegis301** [AI2MS/pyAKI#38]
Right now, a key error is thrown in kdigo.py line 126 when a patient has no entry in one of the input dataframes. This will be the case often for CRRT data. We should not throw a KeyError here but instead just ignore this and not calculate the corresponding stages for this particular patient then. Maybe just fill in np.nan in the corresponding stages col?

**Comment by aegis301** [comment]
Users also should be able to omit Urineoutput data in case they don't have it. Then we should just output the other stages and calculate the stage via the rest.

**Comment by Paul-B98** [comment]
@aegis301 This should be fixed
