### ISSUE TITLE
Bug: Probes not working without preprocessor

### ISSUE THREAD

**Issue by aegis301** [AI2MS/pyAKI#50]
Right now, if no preprocessor is provided, the pipeline stops working. The standard preprocessors are applied by default which is fine but we should provide users with the ability to opt out of preprocessing if the already did preprocessing on their own.

**Comment by Paul-B98** [comment]
This is possible if the time column is converted to a datetime and also the index.

**Comment by Paul-B98** [comment]
@aegis301 I create a preprocessor that will convert the time column into a datetime type if it isn't and use it as the index. If u want to use no preprocessor we should document that the index has to be the time column with a datetime type.
